spring:
  application:
    name: fencaibc-spring-cloud-edu-eureka-open # 服务名称
# 服务端口号
server:
  port: 9999
eureka: #Eureka 相关配置
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    fetchRegistry: false # 是否从其他的服务中心同步服务列表
    registerWithEureka: false # 是否把自己作为服务注册到其他服务注册中心

